update-reminder: true
debug-mode: false

offline-mode: false

data-cache-time: 3600000

teleport:
  delay: 5
  message-type: bossbar
  particles: true


instant-teleport:
  always: false
  worlds: []
  regions: []

cooldown:
  message: 0
  command: 0

number-format:
  locale: "en_US"
  default-format: "#,###.##"
  use-short-format: false

time-formats:
  default: "%hh%:%mm%:%ss%"
  teleportation: "%ss%.%t%"