#
# if you have any questions or suggestions, please do not hesitate and
# join our discord: https://dsc.gg/crownplugins
# we are there to assist you
#

# this is the teleport delay in s
teleport-delay: 5

# set this to true if you don't want to use the teleport animation
# also players in gmc will always be teleported without the animation
instant-teleport: false

# set this to false if you don't want the player do be respawned instantly
instant-respawn: true

# set this to true if you want the player to be teleported to spawn when joining
teleport-to-spawn-on-join: false

# players in this worlds will be teleported without a delay
# this is casesensitive
instant-teleport-worlds: [ ]

# message type: bossbar, actionbar
teleport-message-type: bossbar

# cooldown before sending another command in milliseconds
command-cooldown: 0

# cooldown before sending another chat message in milliseconds
message-cooldown: 0

# DO NOT CHANGE THIS
lastAuthServerCheck: 0
authServer: ""