name: CrownCore
version: 1.3.3
main: de.obey.crown.core.noobf.CrownCore
author: Obey
website: https://builtbybit.com/resources/crowncore.52753/
api-version: '1.20'
folia-supported: true

softdepend:
  - PlaceholderAPI
  - Vault

commands:
  location:
  crowncore:
