name: CrownCore
version: 1.5.3
main: de.obey.crown.core.noobf.CrownCore
author: Obey
website: https://builtbybit.com/resources/crowncore.52753/
api-version: '1.20'
folia-supported: true

libraries:
  - com.h2database:h2:2.3.232
  - org.mariadb.jdbc:mariadb-java-client:3.1.4
  - com.squareup.okhttp3:okhttp:4.12.0
  - com.zaxxer:HikariCP:6.2.1

softdepend:
  - PlaceholderAPI
  - Vault
  - floodgate
  - WorldGuard
  - LuckPerms

loadbefore:
  - FancyNpcs
  - FancyHolograms

commands:
  location:
    description: Command to manage locations
  crowncore:
    description: Command for core
