name: CrownCore
version: 1.0.0
main: de.obey.crown.core.CrownCore
author: Obey
website: dsc.gg/crownplugins
api-version: '1.20'

softdepend:
  - PlaceholderAPI
  - Vault

commands:
  location:
  crowncore:
