name: CrownCore
version: 1.3.9
main: de.obey.crown.core.noobf.CrownCore
author: Obey
website: https://builtbybit.com/resources/crowncore.52753/
api-version: '1.20'
folia-supported: true

libraries:
  - com.squareup.okhttp3:okhttp:4.12.0
  - com.zaxxer:HikariCP:5.1.0

softdepend:
  - PlaceholderAPI
  - Vault

loadbefore:
  - FancyNpcs
  - FancyHolograms

commands:
  location:
    description: Command to manage locations.
  crowncore:
    description: Command for core
